### PR TITLE
Add chartmuseum2oci tool

### PR DESCRIPTION
**Pull request by thcdrt**
Hello,

As discussed in the last Harbor Community Meeting, I developed a script in golang to migrate Helm charts from Chartmuseum to OCI.

I developed it for our customers, I think it may be useful to others Harbor users.

The main difference with the existing tool is that you don't need to setup a local Harbor with replication.
The script does everything, it pulls Helm charts from Chartmuseum and push it to OCI.

A progress bar is displayed during the migration to see the progression and having an estimated ETA:
```bash
$ docker run -ti --rm goharbor/chartmuseum2oci --url $HARBOR_URL --username $HARBOR_USER --password $HARBOR_PASSWORD
2023/06/28 16:17:32 416 Helm charts to migrate from Chartmuseum to OCI
   4% |█████                                                                                                                                        | (19/416, 20 it/min) [56s:19m36s]
```

PS: This PR is a follow-up of https://github.com/goharbor/harbor/pull/18866

Thomas

### CODE REVIEW

**Review by OrlinVasilev — APPROVED** [review]

**Comment by thcdrt** [comment]
@Vad1mo is it ok for you ?

**Review by Vad1mo — APPROVED** [review]

**Comment by thcdrt** [comment]
Thank you.

**Comment by OrlinVasilev** [comment]
Hurray :)

**Comment by cuonghqRose** [comment]
image


I got the above error, even though I exported the password

**Comment by Vad1mo** [comment]
@cuonghqRose, error message is quite clear:

**Missing required - -password flag --password**


So use `--password` instead of `-p`

**Comment by cuonghqRose** [comment]
> @cuonghqRose, error message is quite clear:
> 
> **Missing required - -password flag --password**
> 
> So use `--password` instead of `-p`

thanks for your answer, but I still get the same error despite fixing the --password  flag. I still don't understand where I went wrong, hope you can reply soon. Thank you very much

image
****

**Comment by Vad1mo** [comment]
Sorry, can't reproduce your error. make sure you quote correctly the password env var. Maybe this is the case.




```
docker run -ti --rm goharbor/chartmuseum2oci --url 'https://demo.goharbor.io'  --username admin  --password 'Harbor12345'
2023/08/29 15:24:35 fail to retrieve helm charts to migrate: fail to migrate charts from project dhorse: fail to list harbor projects: response status code does not match any response statuses defined for this endpoint in the swagger spec (status 404): {}
```

**Pull request merged**
